import random


def get_random_text():
    text_options = [
        "Hello, world!",
        "This is a random text.",
        "Programming is fun!",
        "Randomness is the spice of life.",
        "Python is awesome!",
        "Keep calm and code on.",
        "Life is like a box of chocolates.",
        "The only way to do great work is to love what you do.",
        "In the midst of chaos, there is also opportunity.",
        "Creativity is intelligence having fun.",
        "Success is not final, failure is not fatal: It is the courage to continue that counts.",
        "The only limit to our realization of tomorrow will be our doubts of today.",
        "We may encounter many defeats but we must not be defeated.",
        "Be yourself; everyone else is already taken.",
        "Be the change that you wish to see in the world.",
        "No act of kindness, no matter how small, is ever wasted.",
        "Life is what happens when you're busy making other plans.",
        "Believe you can and you're halfway there.",
        "It does not matter how slowly you go as long as you do not stop.",
        "The only thing necessary for the triumph of evil is for good men to do nothing.",
        "Life isn't about finding yourself. Life is about creating yourself.",
        "The best way to predict the future is to create it.",
        "The only true wisdom is in knowing you know nothing.",
        "Yesterday is history, tomorrow is a mystery, but today is a gift. That is why it is called the present.",
        "Life is really simple, but we insist on making it complicated.",
        "The only source of knowledge is experience.",
        "Believe you can and you're halfway there.",
        "Change your thoughts and you change your world.",
        "A journey of a thousand miles begins with a single step.",
        "It is never too late to be what you might have been.",
        "Do not go where the path may lead, go instead where there is no path and leave a trail.",
        "Whatever you are, be a good one.",
        "The mind is everything. What you think you become.",
        "Nothing is impossible, the word itself says 'I'm possible'!",
        "Success is not how high you have climbed, but how you make a positive difference to the world.",
        "Every strike brings me closer to the next home run.",
        "It always seems impossible until it is done.",
        "Act as if what you do makes a difference. It does.",
        "Keep your face always toward the sunshine - and shadows will fall behind you.",
        "What you get by achieving your goals is not as important as what you become by achieving your goals.",
        "You are never too old to set another goal or to dream a new dream.",
        "When you reach the end of your rope, tie a knot in it and hang on.",
        "The future belongs to those who believe in the beauty of their dreams.",
        "Aim for the moon. If you miss, you may hit a star.",
        "You must be the change you wish to see in the world.",
        "Try to be a rainbow in someone's cloud.",
        "Start where you are. Use what you have. Do what you can.",
        "The best way out is always through.",
        "The only way to do great work is to love what you do.",
        "It is never too late to be what you might have been.",
        "Believe you can and you're halfway there.",
        "Success is not how high you have climbed, but how you make a positive difference to the world.",
        "Every strike brings me closer to the next home run.",
        "It always seems impossible until it is done.",
        "Act as if what you do makes a difference. It does.",
        "Keep your face always toward the sunshine - and shadows will fall behind you.",
        "What you get by achieving your goals is not as important as what you become by achieving your goals.",
        "You are never too old to set another goal or to dream a new dream.",
        "When you reach the end of your rope, tie a knot in it and hang on.",
        "The future belongs to those who believe in the beauty of their dreams.",
        "Aim for the moon. If you miss, you may hit a star.",
        "You must be the change you wish to see in the world.",
        "Try to be a rainbow in someone's cloud.",
        "Start where you are. Use what you have. Do what you can.",
        "The best way out is always through.",
        "The only way to do great work is to love what you do.",
        "It is never too late to be what you might have been.",
        "Believe you can and you're halfway there.",
        "Success is not how high you have climbed, but how you make a positive difference to the world.",
        "Every strike brings me closer to the next home run.",
        "It always seems impossible until it is done.",
        "Act as if what you do makes a difference. It does.",
        "Keep your face always toward the sunshine - and shadows will fall behind you.",
        "What you get by achieving your goals is not as important as what you become by achieving your goals.",
        "You are never too old to set another goal or to dream a new dream.",
        "When you reach the end of your rope, tie a knot in it and hang on.",
        "The future belongs to those who believe in the beauty of their dreams.",
        "Aim for the moon. If you miss, you may hit a star.",
        "You must be the change you wish to see in the world.",
        "Try to be a rainbow in someone's cloud.",
        "Start where you are. Use what you have. Do what you can.",
        "The best way out is always through.",
        "The only way to do great work is to love what you do.",
        "It is never too late to be what you might have been.",
        "Believe you can and you're halfway there.",
        "Success is not how high you have climbed, but how you make a positive difference to the world.",
        "Every strike brings me closer to the next home run.",
        "It always seems impossible until it is done.",
        "Act as if what you do makes a difference. It does.",
        "Keep your face always toward the sunshine - and shadows will fall behind you.",
        "What you get by achieving your goals is not as important as what you become by achieving your goals.",
        "You are never too old to set another goal or to dream a new dream.",
        "When you reach the end of your rope, tie a knot in it and hang on.",
        "The future belongs to those who believe in the beauty of their dreams.",
        "Aim for the moon. If you miss, you may hit a star.",
        "You must be the change you wish to see in the world.",
        "Try to be a rainbow in someone's cloud.",
        "Start where you are. Use what you have. Do what you can.",
        "The best way out is always through."
    ]
    return random.choice(text_options)
    # return text_options[index]
